-- Таблица ставок
CREATE TABLE IF NOT EXISTS bets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    bet_id VARCHAR(50) UNIQUE NOT NULL,
    user_id INT NOT NULL,
    match_id VARCHAR(100) NOT NULL,
    line_id VARCHAR(100) NULL,
    match_home VARCHAR(255) NOT NULL,
    match_away VARCHAR(255) NOT NULL,
    match_league VARCHAR(255) NULL,
    outcome_key VARCHAR(50) NOT NULL,
    outcome_label VARCHAR(255) NOT NULL,
    outcome_type VARCHAR(50) NULL,
    outcome_value VARCHAR(50) NULL,
    odd DECIMAL(10, 3) NOT NULL,
    stake DECIMAL(15, 2) NOT NULL,
    potential_win DECIMAL(15, 2) NOT NULL,
    status ENUM('pending', 'active', 'won', 'lost', 'cancelled', 'refunded') DEFAULT 'pending',
    win_amount DECIMAL(15, 2) NULL,
    settled_at TIMESTAMP NULL,
    cancelled_at TIMESTAMP NULL,
    admin_notes TEXT NULL,
    bet_details JSON NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_user_id (user_id),
    INDEX idx_bet_id (bet_id),
    INDEX idx_status (status),
    INDEX idx_match_id (match_id),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
